site_name: Jordan's Doriax Docs

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: .
extra_css:
  - stylesheets/extra.css
theme:
  name: material

extra:
  version:
    provider: mike

nav:
  - Home: index.md
  - Maths:
      - Vector3:
          - Overview: maths/vector3/vector3.md
          - Vector3 Index: maths/vector3/vector3-index.md
          - Vector3 Unit Scale: maths/vector3/vector3-unit-scale.md
          - Vector3 Unit X: maths/vector3/vector3-unit-x.md
          - Vector3 Unit Y: maths/vector3/vector3-unit-y.md
          - Vector3 Unit Z: maths/vector3/vector3-unit-z.md
          - Vector3 X: maths/vector3/vector3-x.md
          - Vector3 Y: maths/vector3/vector3-y.md
          - Vector3 Z: maths/vector3/vector3-z.md
          - Vector3 Zero: maths/vector3/vector3-zero.md
          - Vector3 Operator Index: maths/vector3/vector3-operator-index.md
          - Vector3 Operator Assign: maths/vector3/vector3-operator-assign.md
          - Vector3 Operator Equal: maths/vector3/vector3-operator-equal.md
          - Vector3 Operator Not Equal: maths/vector3/vector3-operator-not-equal.md
          - Vector3 Operator Less: maths/vector3/vector3-operator-less.md
          - Vector3 Operator Greater: maths/vector3/vector3-operator-greater.md
          - Vector3 Operator Add: maths/vector3/vector3-operator-add.md
          - Vector3 Operator Subtract: maths/vector3/vector3-operator-subtract.md
          - Vector3 Operator Multiply: maths/vector3/vector3-operator-multiply.md
          - Vector3 Operator Divide: maths/vector3/vector3-operator-divide.md
          - Vector3 Operator Negate: maths/vector3/vector3-operator-negate.md
          - Vector3 Operator Add Assign: maths/vector3/vector3-operator-add-assign.md
          - Vector3 Operator Subtract Assign: maths/vector3/vector3-operator-subtract-assign.md
          - Vector3 Operator Multiply Assign: maths/vector3/vector3-operator-multiply-assign.md
          - Vector3 Operator Divide Assign: maths/vector3/vector3-operator-divide-assign.md
          - Vector3 Abs Dot Product: maths/vector3/vector3-abs-dot-product.md
          - Vector3 Cross Product: maths/vector3/vector3-cross-product.md
          - Vector3 Distance: maths/vector3/vector3-distance.md
          - Vector3 Dot Product: maths/vector3/vector3-dot-product.md
          - Vector3 Is Valid: maths/vector3/vector3-is-valid.md
          - Vector3 Length: maths/vector3/vector3-length.md
          - Vector3 Lerp: maths/vector3/vector3-lerp.md
          - Vector3 Make Ceil: maths/vector3/vector3-make-ceil.md
          - Vector3 Make Floor: maths/vector3/vector3-make-floor.md
          - Vector3 Mid Point: maths/vector3/vector3-mid-point.md
          - Vector3 Move Towards: maths/vector3/vector3-move-towards.md
          - Vector3 Normalize: maths/vector3/vector3-normalize.md
          - Vector3 Normalized: maths/vector3/vector3-normalized.md
          - Vector3 Normalize L: maths/vector3/vector3-normalize-l.md
          - Vector3 Perpendicular: maths/vector3/vector3-perpendicular.md
          - Vector3 Reflect: maths/vector3/vector3-reflect.md
          - Vector3 Squared Distance: maths/vector3/vector3-squared-distance.md
          - Vector3 Squared Length: maths/vector3/vector3-squared-length.md
          - Vector3 To String: maths/vector3/vector3-to-string.md



      - Vector2:
          - Overview: maths/vector2/vector2.md
          - Vector2 Zero: maths/vector2/vector2-zero.md
          - Vector2 Unit X: maths/vector2/vector2-unit-x.md
          - Vector2 Unit Y: maths/vector2/vector2-unit-y.md
          - Vector2 Negative Unit X: maths/vector2/vector2-negative-unit-x.md
          - Vector2 Negative Unit Y: maths/vector2/vector2-negative-unit-y.md
          - Vector2 Unit Scale: maths/vector2/vector2-unit-scale.md
          - Vector2 X: maths/vector2/vector2-x.md
          - Vector2 Y: maths/vector2/vector2-y.md
          - Vector2 Operator Index: maths/vector2/vector2-operator-index.md
          - Vector2 Operator Assign: maths/vector2/vector2-operator-assign.md
          - Vector2 Operator Equal: maths/vector2/vector2-operator-equal.md
          - Vector2 Operator Not Equal: maths/vector2/vector2-operator-not-equal.md
          - Vector2 Operator Less: maths/vector2/vector2-operator-less.md
          - Vector2 Operator Greater: maths/vector2/vector2-operator-greater.md
          - Vector2 Operator Add: maths/vector2/vector2-operator-add.md
          - Vector2 Operator Subtract: maths/vector2/vector2-operator-subtract.md
          - Vector2 Operator Multiply: maths/vector2/vector2-operator-multiply.md
          - Vector2 Operator Divide: maths/vector2/vector2-operator-divide.md
          - Vector2 Operator Add Assign: maths/vector2/vector2-operator-add-assign.md
          - Vector2 Operator Subtract Assign: maths/vector2/vector2-operator-subtract-assign.md
          - Vector2 Operator Multiply Assign: maths/vector2/vector2-operator-multiply-assign.md
          - Vector2 Abs Dot Product: maths/vector2/vector2-abs-dot-product.md
          - Vector2 Cross Product: maths/vector2/vector2-cross-product.md
          - Vector2 Distance: maths/vector2/vector2-distance.md
          - Vector2 Dot Product: maths/vector2/vector2-dot-product.md
          - Vector2 Is Valid: maths/vector2/vector2-is-valid.md
          - Vector2 Length: maths/vector2/vector2-length.md
          - Vector2 Lerp: maths/vector2/vector2-lerp.md
          - Vector2 Make Ceil: maths/vector2/vector2-make-ceil.md
          - Vector2 Make Floor: maths/vector2/vector2-make-floor.md
          - Vector2 Mid Point: maths/vector2/vector2-mid-point.md
          - Vector2 Move Towards: maths/vector2/vector2-move-towards.md
          - Vector2 Normalize: maths/vector2/vector2-normalize.md
          - Vector2 Normalized: maths/vector2/vector2-normalized.md
          - Vector2 Normalized Copy: maths/vector2/vector2-normalized-copy.md
          - Vector2 Normalize L: maths/vector2/vector2-normalize-l.md
          - Vector2 Perpendicular: maths/vector2/vector2-perpendicular.md
          - Vector2 Reflect: maths/vector2/vector2-reflect.md
          - Vector2 Squared Distance: maths/vector2/vector2-squared-distance.md
          - Vector2 Squared Length: maths/vector2/vector2-squared-length.md
          - Vector2 Swap: maths/vector2/vector2-swap.md
          - Vector2 To String: maths/vector2/vector2-to-string.md
      - Vector4:
          - Overview: maths/vector4/vector4.md
          - Vector4 Zero: maths/vector4/vector4-zero.md
          - Vector4 Unit X: maths/vector4/vector4-unit-x.md
          - Vector4 Unit Y: maths/vector4/vector4-unit-y.md
          - Vector4 Unit Z: maths/vector4/vector4-unit-z.md
          - Vector4 Unit W: maths/vector4/vector4-unit-w.md
          - Vector4 Unit Scale: maths/vector4/vector4-unit-scale.md
          - Vector4 X: maths/vector4/vector4-x.md
          - Vector4 Y: maths/vector4/vector4-y.md
          - Vector4 Z: maths/vector4/vector4-z.md
          - Vector4 W: maths/vector4/vector4-w.md
          - Vector4 Operator Index: maths/vector4/vector4-operator-index.md
          - Vector4 Operator Assign: maths/vector4/vector4-operator-assign.md
          - Vector4 Operator Equal: maths/vector4/vector4-operator-equal.md
          - Vector4 Operator Not Equal: maths/vector4/vector4-operator-not-equal.md
          - Vector4 Operator Less: maths/vector4/vector4-operator-less.md
          - Vector4 Operator Greater: maths/vector4/vector4-operator-greater.md
          - Vector4 Operator Add: maths/vector4/vector4-operator-add.md
          - Vector4 Operator Subtract: maths/vector4/vector4-operator-subtract.md
          - Vector4 Operator Multiply: maths/vector4/vector4-operator-multiply.md
          - Vector4 Operator Divide: maths/vector4/vector4-operator-divide.md
          - Vector4 Operator Add Assign: maths/vector4/vector4-operator-add-assign.md
          - Vector4 Operator Subtract Assign: maths/vector4/vector4-operator-subtract-assign.md
          - Vector4 Operator Multiply Assign: maths/vector4/vector4-operator-multiply-assign.md
          - Vector4 Operator Divide Assign: maths/vector4/vector4-operator-divide-assign.md
          - Vector4 Divide By W: maths/vector4/vector4-divide-by-w.md
          - Vector4 Dot Product: maths/vector4/vector4-dot-product.md
          - Vector4 Is NaN: maths/vector4/vector4-is-nan.md
          - Vector4 Is Valid: maths/vector4/vector4-is-valid.md
          - Vector4 Swap: maths/vector4/vector4-swap.md
          - Vector4 To String: maths/vector4/vector4-to-string.md
      - Plane:
          - Overview: maths/plane/plane.md
          - Plane Normal: maths/plane/plane-normal.md
          - Plane D: maths/plane/plane-d.md
          - Plane Side: maths/plane/plane-side.md
          - Plane Operator Negate: maths/plane/plane-operator-negate.md
          - Plane Operator Equal: maths/plane/plane-operator-equal.md
          - Plane Operator Not Equal: maths/plane/plane-operator-not-equal.md
          - Plane Get Distance: maths/plane/plane-get-distance.md
          - Plane Get Side: maths/plane/plane-get-side.md
          - Plane Redefine: maths/plane/plane-redefine.md
          - Plane Project Vector: maths/plane/plane-project-vector.md
          - Plane Normalize: maths/plane/plane-normalize.md
          - Plane Normalized: maths/plane/plane-normalized.md
      - Sphere:
          - Overview: maths/sphere/sphere.md
          - Sphere Center: maths/sphere/sphere-center.md
          - Sphere Radius: maths/sphere/sphere-radius.md
          - Sphere Operator Assign: maths/sphere/sphere-operator-assign.md
          - Sphere Operator Equal: maths/sphere/sphere-operator-equal.md
          - Sphere Operator Not Equal: maths/sphere/sphere-operator-not-equal.md
          - Sphere Contains: maths/sphere/sphere-contains.md
          - Sphere Intersects Sphere: maths/sphere/sphere-intersects-sphere.md
          - Sphere Intersects AABB: maths/sphere/sphere-intersects-aabb.md
          - Sphere Intersects OBB: maths/sphere/sphere-intersects-obb.md
          - Sphere Intersects Plane: maths/sphere/sphere-intersects-plane.md
          - Sphere Intersects Point: maths/sphere/sphere-intersects-point.md
          - Sphere Merge: maths/sphere/sphere-merge.md
          - Sphere Surface Area: maths/sphere/sphere-surface-area.md
          - Sphere Volume: maths/sphere/sphere-volume.md
      - Rect: maths/rect/rect.md
      - Ray:
          - Overview: maths/ray/ray.md
          - Ray Return: maths/ray/ray-return.md

  - Core:
      - ECS:
          - Entity: core/ecs/entity.md
      - Object:
          - Object: core/object/object.md
          - Physics:
              - 2D:
                  - AABB: core/object/physics/2D/aabb/aabb.md
                  - Body2D: core/object/physics/2D/body-2d/body-2d.md
              - Body Type: core/object/physics/body-type.md
              - Box Type: core/object/physics/box-type.md
              - 3D:
                  - OBB: core/object/physics/3D/obb/obb.md